/* The following code was generated by JFlex 1.4.3 on 8/25/18 10:49 AM */

package analizador;
import static analizador.Token.*;

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 8/25/18 10:49 AM from the specification file
 * <tt>C:/Users/Jose Mansilla/Documents/Proyecto_1_AnalizadorLexico-master/analizadorLexico-Java/src/analizador/Lexer.flex</tt>
 */
class Lexer {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\77\1\2\2\0\1\1\22\0\1\72\1\44\1\65\1\66"+
    "\1\70\1\40\1\45\1\71\1\54\1\55\1\4\1\36\1\50\1\37"+
    "\1\51\1\3\1\62\11\100\1\75\1\47\1\41\1\42\1\43\1\74"+
    "\1\67\1\34\1\64\1\64\1\64\1\61\1\64\7\60\1\33\11\60"+
    "\1\63\2\60\1\52\1\73\1\53\1\66\1\60\1\76\1\23\1\14"+
    "\1\22\1\10\1\16\1\24\1\21\1\25\1\7\1\60\1\32\1\15"+
    "\1\27\1\11\1\6\1\30\1\60\1\20\1\17\1\12\1\13\1\5"+
    "\1\31\1\26\1\35\1\60\1\56\1\46\1\57\1\66\uff81\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\2\3\16\4\1\3\1\5\1\6"+
    "\1\7\1\3\2\1\1\10\1\11\1\12\1\13\1\14"+
    "\1\15\1\16\1\17\1\20\1\21\1\22\1\23\1\24"+
    "\1\22\1\25\1\26\1\27\1\22\1\21\1\30\1\0"+
    "\1\6\2\4\1\31\1\4\1\32\22\4\2\0\1\33"+
    "\1\34\1\0\1\35\1\36\1\0\1\37\2\0\1\37"+
    "\1\0\1\40\2\30\1\0\1\4\1\31\17\4\1\31"+
    "\4\4\1\31\4\0\3\4\1\41\1\31\12\4\1\0"+
    "\1\21\1\35\13\4\1\42\1\4\1\43\4\4\1\44"+
    "\5\4\1\45\1\4\1\46\1\4\1\47\3\4\1\50"+
    "\1\51";

  private static int [] zzUnpackAction() {
    int [] result = new int[167];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\101\0\101\0\202\0\101\0\303\0\u0104\0\u0145"+
    "\0\u0186\0\u01c7\0\u0208\0\u0249\0\u028a\0\u02cb\0\u030c\0\u034d"+
    "\0\u038e\0\u03cf\0\u0410\0\u0451\0\u0492\0\u04d3\0\u0514\0\u0555"+
    "\0\u0596\0\u05d7\0\101\0\101\0\u0618\0\u0659\0\101\0\u069a"+
    "\0\101\0\u06db\0\101\0\u071c\0\u075d\0\101\0\101\0\u079e"+
    "\0\101\0\u07df\0\101\0\101\0\u0820\0\u0861\0\u08a2\0\101"+
    "\0\u08e3\0\u0924\0\u0104\0\u0965\0\u09a6\0\u09e7\0\u0a28\0\u0a69"+
    "\0\u0aaa\0\u0aeb\0\u0b2c\0\u0b6d\0\u0bae\0\u0bef\0\u0c30\0\u0c71"+
    "\0\u0cb2\0\u0cf3\0\u0d34\0\u0d75\0\u0db6\0\u0df7\0\u0e38\0\u0e79"+
    "\0\u0eba\0\101\0\101\0\u0efb\0\u0f3c\0\u0f7d\0\u075d\0\101"+
    "\0\u0fbe\0\u079e\0\u079e\0\u0fff\0\101\0\u1040\0\101\0\u1081"+
    "\0\u10c2\0\u1103\0\u1144\0\u1185\0\u11c6\0\u1207\0\u1248\0\u1289"+
    "\0\u12ca\0\u130b\0\u134c\0\u138d\0\u13ce\0\u140f\0\u1450\0\u1491"+
    "\0\u14d2\0\u1513\0\u1554\0\u1595\0\u15d6\0\u1617\0\u1658\0\u1699"+
    "\0\u16da\0\u171b\0\u175c\0\u179d\0\u17de\0\u181f\0\u0104\0\u1860"+
    "\0\u18a1\0\u18e2\0\u1923\0\u1964\0\u19a5\0\u19e6\0\u1a27\0\u1a68"+
    "\0\u1aa9\0\u1aea\0\u1b2b\0\101\0\u1b6c\0\u1bad\0\u1bee\0\u1c2f"+
    "\0\u1c70\0\u1cb1\0\u1cf2\0\u1d33\0\u1d74\0\u1db5\0\u1df6\0\u1e37"+
    "\0\u0104\0\u1e78\0\101\0\u1eb9\0\u1efa\0\u1f3b\0\u1f7c\0\u0104"+
    "\0\u1fbd\0\u1ffe\0\u203f\0\u2080\0\u20c1\0\u0104\0\u2102\0\u0104"+
    "\0\u2143\0\u0104\0\u2184\0\u21c5\0\u2206\0\u0104\0\u0104";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[167];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\2\3\1\4\1\5\1\6\1\7\1\10\1\11"+
    "\1\12\1\13\1\7\1\14\1\7\1\15\1\16\1\17"+
    "\1\7\1\20\1\7\1\21\4\7\1\22\1\7\1\23"+
    "\2\7\1\5\1\24\1\5\1\25\1\26\1\27\1\30"+
    "\1\31\1\32\1\33\1\34\1\35\1\36\1\37\1\40"+
    "\1\41\1\42\1\43\2\7\1\44\2\7\1\45\1\2"+
    "\1\46\1\47\1\50\1\3\1\51\1\52\1\53\1\54"+
    "\1\3\1\55\104\0\1\56\1\57\35\0\1\60\43\0"+
    "\1\7\1\61\27\7\22\0\5\7\13\0\1\7\5\0"+
    "\31\7\22\0\5\7\13\0\1\7\5\0\4\7\1\62"+
    "\12\7\1\63\2\7\1\64\6\7\22\0\5\7\13\0"+
    "\1\7\5\0\1\7\1\65\27\7\22\0\5\7\13\0"+
    "\1\7\5\0\6\7\1\66\22\7\22\0\5\7\13\0"+
    "\1\7\5\0\13\7\1\67\4\7\1\70\10\7\22\0"+
    "\5\7\13\0\1\7\5\0\1\7\1\71\11\7\1\72"+
    "\15\7\22\0\5\7\13\0\1\7\5\0\10\7\1\73"+
    "\10\7\1\74\7\7\22\0\5\7\13\0\1\7\5\0"+
    "\5\7\1\75\16\7\1\76\4\7\22\0\5\7\13\0"+
    "\1\7\5\0\11\7\1\77\17\7\22\0\5\7\13\0"+
    "\1\7\5\0\1\7\1\100\6\7\1\101\20\7\22\0"+
    "\5\7\13\0\1\7\5\0\1\7\1\102\4\7\1\103"+
    "\1\7\1\104\5\7\1\105\12\7\22\0\5\7\13\0"+
    "\1\7\5\0\20\7\1\106\10\7\22\0\5\7\13\0"+
    "\1\7\5\0\11\7\1\107\17\7\22\0\5\7\13\0"+
    "\1\7\62\0\1\110\15\0\1\110\42\0\1\5\31\0"+
    "\1\111\46\0\1\112\1\60\77\0\1\5\100\0\1\113"+
    "\100\0\1\60\2\0\1\5\101\0\1\5\74\0\1\60"+
    "\111\0\1\5\64\0\1\114\15\0\1\5\102\0\1\5"+
    "\72\0\1\115\10\0\1\55\1\116\14\0\1\55\3\0"+
    "\53\117\1\0\6\117\1\120\4\117\1\121\3\117\2\0"+
    "\1\117\3\0\53\122\1\0\6\122\1\0\3\122\1\123"+
    "\1\124\3\122\2\0\1\122\43\0\1\125\106\0\1\115"+
    "\10\0\1\55\15\0\1\55\1\56\1\126\1\127\76\56"+
    "\4\130\1\0\74\130\5\0\2\7\1\131\26\7\22\0"+
    "\5\7\13\0\1\7\5\0\5\7\1\132\7\7\1\133"+
    "\13\7\22\0\5\7\13\0\1\7\5\0\23\7\1\134"+
    "\5\7\22\0\5\7\13\0\1\7\5\0\6\7\1\135"+
    "\22\7\22\0\5\7\13\0\1\7\5\0\10\7\1\136"+
    "\20\7\22\0\5\7\13\0\1\7\5\0\6\7\1\137"+
    "\22\7\22\0\5\7\13\0\1\7\5\0\2\7\1\140"+
    "\26\7\22\0\5\7\13\0\1\7\5\0\1\7\1\141"+
    "\27\7\22\0\5\7\13\0\1\7\5\0\11\7\1\142"+
    "\17\7\22\0\5\7\13\0\1\7\5\0\12\7\1\143"+
    "\16\7\22\0\5\7\13\0\1\7\5\0\5\7\1\144"+
    "\23\7\22\0\5\7\13\0\1\7\5\0\13\7\1\145"+
    "\15\7\22\0\5\7\13\0\1\7\5\0\2\7\1\146"+
    "\26\7\22\0\5\7\13\0\1\7\5\0\5\7\1\147"+
    "\23\7\22\0\5\7\13\0\1\7\5\0\4\7\1\150"+
    "\24\7\22\0\5\7\13\0\1\7\5\0\16\7\1\151"+
    "\12\7\22\0\5\7\13\0\1\7\5\0\13\7\1\152"+
    "\15\7\22\0\5\7\13\0\1\7\5\0\4\7\1\153"+
    "\24\7\22\0\5\7\13\0\1\7\5\0\1\7\1\154"+
    "\27\7\22\0\5\7\13\0\1\7\5\0\10\7\1\155"+
    "\20\7\22\0\5\7\13\0\1\7\5\0\2\7\1\156"+
    "\26\7\22\0\5\7\13\0\1\7\5\0\24\7\1\157"+
    "\4\7\22\0\5\7\13\0\1\7\51\0\1\115\10\0"+
    "\1\110\15\0\1\110\30\0\1\160\132\0\1\161\15\0"+
    "\1\161\61\0\1\162\1\115\15\0\1\115\34\0\1\116"+
    "\24\0\2\116\1\0\1\116\13\0\1\116\3\0\62\117"+
    "\1\120\4\117\1\121\3\117\2\0\1\117\3\0\62\122"+
    "\1\0\3\122\1\123\1\124\3\122\2\0\1\122\2\0"+
    "\1\127\76\0\4\130\1\163\74\130\5\0\3\7\1\63"+
    "\25\7\22\0\5\7\13\0\1\7\5\0\11\7\1\164"+
    "\17\7\22\0\5\7\13\0\1\7\5\0\10\7\1\165"+
    "\20\7\22\0\5\7\13\0\1\7\5\0\10\7\1\166"+
    "\20\7\22\0\5\7\13\0\1\7\5\0\7\7\1\156"+
    "\21\7\22\0\5\7\13\0\1\7\5\0\10\7\1\63"+
    "\20\7\22\0\5\7\13\0\1\7\5\0\11\7\1\167"+
    "\17\7\22\0\5\7\13\0\1\7\5\0\12\7\1\63"+
    "\16\7\22\0\5\7\13\0\1\7\5\0\10\7\1\170"+
    "\20\7\22\0\5\7\13\0\1\7\5\0\16\7\1\171"+
    "\12\7\22\0\5\7\13\0\1\7\5\0\11\7\1\63"+
    "\17\7\22\0\5\7\13\0\1\7\5\0\11\7\1\172"+
    "\17\7\22\0\5\7\13\0\1\7\5\0\2\7\1\173"+
    "\26\7\22\0\5\7\13\0\1\7\5\0\5\7\1\174"+
    "\23\7\22\0\5\7\13\0\1\7\5\0\6\7\1\175"+
    "\22\7\22\0\5\7\13\0\1\7\5\0\5\7\1\176"+
    "\23\7\22\0\5\7\13\0\1\7\5\0\12\7\1\140"+
    "\16\7\22\0\5\7\13\0\1\7\5\0\11\7\1\177"+
    "\17\7\22\0\5\7\13\0\1\7\5\0\15\7\1\200"+
    "\13\7\22\0\5\7\13\0\1\7\5\0\16\7\1\201"+
    "\12\7\22\0\5\7\13\0\1\7\5\0\12\7\1\137"+
    "\16\7\22\0\5\7\13\0\1\7\5\0\10\7\1\143"+
    "\20\7\22\0\5\7\13\0\1\7\5\0\27\7\1\202"+
    "\1\7\22\0\5\7\13\0\1\7\25\0\1\203\130\0"+
    "\1\204\4\0\1\161\15\0\1\161\36\0\2\205\41\0"+
    "\3\130\1\127\1\163\74\130\5\0\13\7\1\206\15\7"+
    "\22\0\5\7\13\0\1\7\5\0\6\7\1\207\22\7"+
    "\22\0\5\7\13\0\1\7\5\0\11\7\1\210\17\7"+
    "\22\0\5\7\13\0\1\7\5\0\11\7\1\211\17\7"+
    "\22\0\5\7\13\0\1\7\5\0\25\7\1\63\3\7"+
    "\22\0\5\7\13\0\1\7\5\0\4\7\1\212\24\7"+
    "\22\0\5\7\13\0\1\7\5\0\4\7\1\213\24\7"+
    "\22\0\5\7\13\0\1\7\5\0\15\7\1\214\13\7"+
    "\22\0\5\7\13\0\1\7\5\0\13\7\1\215\15\7"+
    "\22\0\5\7\13\0\1\7\5\0\2\7\1\216\26\7"+
    "\22\0\5\7\13\0\1\7\5\0\16\7\1\217\12\7"+
    "\22\0\5\7\13\0\1\7\5\0\5\7\1\220\23\7"+
    "\22\0\5\7\13\0\1\7\5\0\5\7\1\221\23\7"+
    "\22\0\5\7\13\0\1\7\5\0\13\7\1\222\15\7"+
    "\22\0\5\7\13\0\1\7\30\0\1\223\132\0\1\205"+
    "\15\0\1\205\5\0\17\7\1\224\11\7\22\0\5\7"+
    "\13\0\1\7\5\0\3\7\1\225\25\7\22\0\5\7"+
    "\13\0\1\7\5\0\22\7\1\226\6\7\22\0\5\7"+
    "\13\0\1\7\5\0\16\7\1\227\12\7\22\0\5\7"+
    "\13\0\1\7\5\0\3\7\1\140\25\7\22\0\5\7"+
    "\13\0\1\7\5\0\14\7\1\63\14\7\22\0\5\7"+
    "\13\0\1\7\5\0\20\7\1\230\10\7\22\0\5\7"+
    "\13\0\1\7\5\0\4\7\1\63\24\7\22\0\5\7"+
    "\13\0\1\7\5\0\4\7\1\231\24\7\22\0\5\7"+
    "\13\0\1\7\5\0\15\7\1\232\13\7\22\0\5\7"+
    "\13\0\1\7\5\0\2\7\1\233\26\7\22\0\5\7"+
    "\13\0\1\7\5\0\13\7\1\234\15\7\22\0\5\7"+
    "\13\0\1\7\5\0\16\7\1\235\12\7\22\0\5\7"+
    "\13\0\1\7\5\0\11\7\1\236\17\7\22\0\5\7"+
    "\13\0\1\7\5\0\11\7\1\237\17\7\22\0\5\7"+
    "\13\0\1\7\5\0\4\7\1\240\24\7\22\0\5\7"+
    "\13\0\1\7\5\0\6\7\1\241\22\7\22\0\5\7"+
    "\13\0\1\7\5\0\20\7\1\242\10\7\22\0\5\7"+
    "\13\0\1\7\5\0\1\7\1\243\27\7\22\0\5\7"+
    "\13\0\1\7\5\0\16\7\1\244\12\7\22\0\5\7"+
    "\13\0\1\7\5\0\15\7\1\143\13\7\22\0\5\7"+
    "\13\0\1\7\5\0\4\7\1\245\24\7\22\0\5\7"+
    "\13\0\1\7\5\0\11\7\1\246\17\7\22\0\5\7"+
    "\13\0\1\7\5\0\4\7\1\247\24\7\22\0\5\7"+
    "\13\0\1\7\5\0\30\7\1\63\22\0\5\7\13\0"+
    "\1\7\5\0\5\7\1\140\23\7\22\0\5\7\13\0"+
    "\1\7";

  private static int [] zzUnpackTrans() {
    int [] result = new int[8775];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\2\11\1\1\1\11\25\1\2\11\2\1\1\11"+
    "\1\1\1\11\1\1\1\11\2\1\2\11\1\1\1\11"+
    "\1\1\2\11\2\1\1\0\1\11\27\1\2\0\2\11"+
    "\1\0\2\1\1\0\1\11\2\0\1\1\1\0\1\11"+
    "\1\1\1\11\1\0\27\1\4\0\17\1\1\0\1\11"+
    "\16\1\1\11\24\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[167];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
//Variables globales para ser accedidas después
public String lexeme;
public int linea;


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Lexer(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  Lexer(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 158) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

	// numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public Token yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      for (zzCurrentPosL = zzStartRead; zzCurrentPosL < zzMarkedPosL;
                                                             zzCurrentPosL++) {
        switch (zzBufferL[zzCurrentPosL]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          zzR = false;
          break;
        case '\r':
          yyline++;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
          }
          break;
        default:
          zzR = false;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 36: 
          { {lexeme=yytext(); return SELEC;}
          }
        case 42: break;
        case 12: 
          { lexeme=yytext(); return PAF;
          }
        case 43: break;
        case 4: 
          { lexeme=yytext(); return ID;
          }
        case 44: break;
        case 11: 
          { lexeme=yytext(); return PAI;
          }
        case 45: break;
        case 17: 
          { lexeme=yytext(); return INT;
          }
        case 46: break;
        case 27: 
          { lexeme=yytext(); return COMPARACION;
          }
        case 47: break;
        case 28: 
          { lexeme=yytext(); return DIFERENTE;
          }
        case 48: break;
        case 37: 
          { {lexeme=yytext(); return INCLUI;}
          }
        case 49: break;
        case 41: 
          { {lexeme=yytext(); return FUN;}
          }
        case 50: break;
        case 22: 
          { lexeme=yytext(); return SIGNIN;
          }
        case 51: break;
        case 25: 
          { lexeme=yytext(); return PALABRARESERVADA;
          }
        case 52: break;
        case 29: 
          { {lexeme=yytext(); return REAL;}
          }
        case 53: break;
        case 8: 
          { lexeme=yytext(); return PUNTOYCOMA;
          }
        case 54: break;
        case 23: 
          { lexeme=yytext(); return DOSPUNTOS;
          }
        case 55: break;
        case 24: 
          { lexeme=yytext(); return COMMENT;
          }
        case 56: break;
        case 1: 
          { lexeme=yytext();linea = yyline; return ERROR;
          }
        case 57: break;
        case 33: 
          { lexeme=yytext(); return TIPODEDATOL;
          }
        case 58: break;
        case 7: 
          { lexeme=yytext(); return ETF;
          }
        case 59: break;
        case 5: 
          { lexeme=yytext(); return ETI;
          }
        case 60: break;
        case 15: 
          { lexeme=yytext(); return LLAVEA;
          }
        case 61: break;
        case 20: 
          { lexeme=yytext(); return VARIABLE;
          }
        case 62: break;
        case 10: 
          { lexeme=yytext(); return PUNTO;
          }
        case 63: break;
        case 26: 
          { {lexeme=yytext(); return HMIENTR;}
          }
        case 64: break;
        case 21: 
          { lexeme=yytext(); return SLASH;
          }
        case 65: break;
        case 32: 
          { lexeme=yytext(); return FINPHP;
          }
        case 66: break;
        case 40: 
          { {lexeme=yytext(); return CONTIN;}
          }
        case 67: break;
        case 39: 
          { {lexeme=yytext(); return PARAC;}
          }
        case 68: break;
        case 2: 
          { lexeme=yytext(); return ESPACIO;
          }
        case 69: break;
        case 13: 
          { lexeme=yytext(); return PAA;
          }
        case 70: break;
        case 18: 
          { lexeme=yytext(); return COMILLA;
          }
        case 71: break;
        case 16: 
          { lexeme=yytext(); return LLAVEC;
          }
        case 72: break;
        case 35: 
          { lexeme=yytext(); return INICIOPHP;
          }
        case 73: break;
        case 6: 
          { lexeme=yytext(); return ASIGNACION;
          }
        case 74: break;
        case 30: 
          { {lexeme=yytext(); return HEXA;}
          }
        case 75: break;
        case 3: 
          { lexeme=yytext(); return OPERADORARITMETICO;
          }
        case 76: break;
        case 9: 
          { lexeme=yytext(); return COMA;
          }
        case 77: break;
        case 31: 
          { lexeme=yytext(); return TEXTO;
          }
        case 78: break;
        case 38: 
          { {lexeme=yytext(); return BOOL;}
          }
        case 79: break;
        case 19: 
          { lexeme=yytext(); return ARR;
          }
        case 80: break;
        case 14: 
          { lexeme=yytext(); return PAC;
          }
        case 81: break;
        case 34: 
          { lexeme=yytext(); return REA;
          }
        case 82: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            return null;
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
