/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

package analizador;

/**
 *
 * @author Carlos
 */
public enum Token {
PALABRARESERVADA,TIPODEDATOL,SI,PAA,PUNTO,HEXA,REAL,DOSPUNTOS,SLASH,SIGNIN,ARR,ETI,ETF,PAI,PAF,ESPACIO,ARGBD,BOOL,CONSTP,PAC,TEXTO,VARPRE,FUN,ACCDB,COMA,MIENTR,HMIENTR,PARA,PARAC,SELEC,INCLUI,CONTIN,RET,BREA,ELS,PUNTOYCOMA, ID,INT,INICIOPHP,FINPHP,LLAVEA,LLAVEC,ASIGNACION,COMPARACION,DIFERENTE,OPERADORLOGICO, OPERADORARITMETICO, IDENTIFICADOR, VARIABLE, CONSTANTE, ESTRUCTURADECONTROL,COMMENT,COMILLA, VARIABLEPREDETERMINADA, FUNCION, COMENTARIO, ACCESOBASEDEDATOS,ERROR,ENT,REA,CADENA
}
