
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Nov 20 00:12:41 CST 2018
//----------------------------------------------------

package analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int HERENCIA = 15;
  public static final int PUNTOYCOMA = 4;
  public static final int M_OC = 32;
  public static final int IMPRIMIR = 24;
  public static final int IMPLEMENTA = 16;
  public static final int ENTERO = 37;
  public static final int SI = 18;
  public static final int OBTENER_BYTES = 42;
  public static final int TDS = 9;
  public static final int VD = 10;
  public static final int ROMPE = 23;
  public static final int LEER_EN = 33;
  public static final int CONSTANTE = 48;
  public static final int IDENTIFICADOR = 3;
  public static final int IGUAL = 45;
  public static final int OPERADORESL = 47;
  public static final int SINO = 19;
  public static final int TDE = 5;
  public static final int SET_BYTES = 43;
  public static final int MIENTRAS = 21;
  public static final int TDD = 6;
  public static final int TDB = 7;
  public static final int OPERADORESC = 46;
  public static final int OPERADORESA = 2;
  public static final int ESTO = 25;
  public static final int DECIMAL = 36;
  public static final int EOF = 0;
  public static final int CLASE = 14;
  public static final int error = 1;
  public static final int NULO = 39;
  public static final int COMA = 13;
  public static final int MENOS = 44;
  public static final int NEGACION = 31;
  public static final int PAR_C = 12;
  public static final int RETORNA = 22;
  public static final int PAR_A = 11;
  public static final int NUEVO_A = 41;
  public static final int NUEVO = 40;
  public static final int LL_C = 30;
  public static final int LL_A = 29;
  public static final int PUNTO = 35;
  public static final int INTERFAZ = 17;
  public static final int BOOLCONST = 8;
  public static final int LEER_LIN = 34;
  public static final int PARA = 20;
  public static final int TEXTO = 38;
  public static final int CORCH_C = 28;
  public static final int CORCH_A = 26;
  public static final int CORCH = 27;
}

