
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Oct 06 12:31:34 CST 2018
//----------------------------------------------------

package analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int HERENCIA = 16;
  public static final int PUNTOYCOMA = 5;
  public static final int M_OC = 34;
  public static final int IMPRIMIR = 25;
  public static final int IMPLEMENTA = 17;
  public static final int ENTERO = 39;
  public static final int SI = 19;
  public static final int OBTENER_BYTES = 44;
  public static final int PARENTESIS = 27;
  public static final int TDS = 9;
  public static final int VD = 11;
  public static final int LEER_EN = 35;
  public static final int ROMPE = 24;
  public static final int IDENTIFICADOR = 4;
  public static final int IGUAL = 47;
  public static final int SINO = 20;
  public static final int TDE = 6;
  public static final int SET_BYTES = 45;
  public static final int MIENTRAS = 22;
  public static final int TDD = 7;
  public static final int TDB = 8;
  public static final int OPERADORESA = 2;
  public static final int ESTO = 26;
  public static final int DECIMAL = 38;
  public static final int EOF = 0;
  public static final int CLASE = 15;
  public static final int error = 1;
  public static final int NULO = 41;
  public static final int COMA = 14;
  public static final int MENOS = 46;
  public static final int NEGACION = 33;
  public static final int PAR_C = 13;
  public static final int RETORNA = 23;
  public static final int PAR_A = 12;
  public static final int NUEVO_A = 43;
  public static final int NUEVO = 42;
  public static final int LL_C = 31;
  public static final int LL_A = 30;
  public static final int PUNTO = 37;
  public static final int INTERFAZ = 18;
  public static final int LLAVES = 32;
  public static final int HEXADECIMAL = 3;
  public static final int LEER_LIN = 36;
  public static final int PARA = 21;
  public static final int TEXTO = 40;
  public static final int CORCH_C = 29;
  public static final int CORCH_A = 28;
  public static final int CORCH = 10;
}

